# Generated by Django 5.2.12 on 2026-06-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_message_chat_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageimage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat_app.message'),
        ),
    ]
